enableImmutableInstalls: false

httpTimeout: 300000

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x64
    - ia32
    - arm64
  os:
    - current
    - darwin
    - linux
    - win32
